#!/bin/bash

altDir=$(pwd)
origRegex="$1"
newRegex="$2"


if [ -z "$1" ]; then
	echo "No first argument was provided. Exiting." >&2
	exit 1
fi

if [ "$1" == "-d" ]; then
	# user-specified directory
	altDir="$2"
	if [ ! -d $altDir ]; then
		echo "Error: directory $altDir not found." >&2
		exit 1
	else
		origRegex="$3"
		newRegex="$4"
		canary="$5" # should be blank
	fi
else
	canary="$3" # should be blank
fi

fileList=(`ls $altDir`)

if [ -n "$canary" ] ; then # canary isn't blank
	echo "Too many arguments provided. Exiting." >&2
	exit 1
fi

# change to altdir (changes not saved after exit)
cd $altDir

wereChanges=0
for k in "${fileList[@]}"; do
	old="$k"
	new="$(echo $k | sed s/$origRegex/$newRegex/ )"
	if [ "$new" != "$old" ] && [ "$new" != "$0" ] && [ "./$new" != "$0" ]
	then
		echo "$old was changed to $new"
		mv "$old" "$new"
		wereChanges=1
	fi
done

if [ $wereChanges = 0 ]; then
	echo "No files were moved" >&2
fi

exit 0
